### ISSUE TITLE
Add picolibc [RISC-V/AVR?/ARM?]

### ISSUE THREAD

**Issue by Irvise** [alire-project/GNAT-FSF-builds#46]
I am opening this issue just to  track the potential use of [picolibc](https://github.com/picolibc/picolibc) in the RISC-V toolchain and potentially AVR too.

Afaik, the riscv64 toolchain has no libc included. AVR has avr-libc. I do not know the state of arm (32bit). Picolibc is designed to add a basic libc system for deeply embedded targets and RTOSes. It is also updated frequently and adds some advance functionality, such as initial support for `long double`. Some toolchains already use picolibc instead of newlibc such as Litex.

Picolibc is built from avr-libc and newlibc, so we could potentially deprecate newlibc.

Once again, this is just to help me keep track of this idea. I am currently not asking it to be added to the builds.

Regards,
Fer

**Comment by Fabien-Chouteau** [comment]
`arm-elf` and `riscv64-elf` both come with `newlib` and as you said there's `avr-libc` for `avr-elf` so we are all covered in terms of libc.

We are not looking to switch to different libc at the moment because 1) it's extra work for no clear benefits, 2) it would differentiate this build from other GNAT builds .
